### ISSUE TITLE
Multiple operations over one WebSocket connection.

### ISSUE THREAD

**Issue by BratSinot** [obmarg/graphql-ws-client#18]
For example this cause panic:
```rust
        let mut stream = client
            .streaming_operation(WorkspaceVoiceVoicemail::build(()))
            .await;

        for _ in 0..5 {
            let data = stream
                .next()
                .await
                .unwrap()
                .data
                .unwrap();
        }

        stream = client
            .streaming_operation(WorkspaceVoiceVoicemail::build(()))
            .await;

        for _ in 0..5 {
            let data = stream
                .next()
                .await
                .unwrap()
                .data
                .unwrap();
        }
```
Somehow need send `Complete` to server when the stream is droping.

**Comment by BratSinot** [comment]
Hm… But I have socket (`client`) I can send message by myself.
So, I don't know which more idiomatic in Rust by destructor (`drop`) or manual.

**Comment by obmarg** [comment]
I had some vague plans for dealing with stuff like this.  At the moment `StreamingOperation` just returns an anonymous `impl Stream`, but I figured it should probably return a concrete type that implements `Stream`.

That'll give us a place to stick any extra functionality that we need - checks for errors, functions to disconnect, and I assume we could put a custom drop impl on it to send that `Complete` message.  Imagine it might need to hold a copy of the clients `sender_sink` so that it can send a `Complete` message using it...

**Comment by BratSinot** [comment]
Hm... This is definitely Duplicate of #7
