### ISSUE TITLE
Using with tokio

### ISSUE THREAD

**Issue by BratSinot** [obmarg/graphql-ws-client#21]
By the way, how use with tokio?
This code give me panic: `thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.',  #C:\Users\asinotov\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.6.0\src\runtime\blocking\shutdown.rs:51:21`
```rust
#[tokio::main]
async fn main() {
    let mut request = "ws://localhost:5000/graphql".into_client_request().unwrap();
    request.headers_mut().insert(
        "Sec-WebSocket-Protocol",
        HeaderValue::from_str("graphql-transport-ws").unwrap(),
    );

    let (connection, res) = async_tungstenite::tokio::connect_async(request)
        .await
        .unwrap();

    let (sink, stream) = connection.split();

    assert_eq!(StatusCode::SWITCHING_PROTOCOLS, res.status());

    let mut _client = CynicClientBuilder::new()
        .payload("data")
        .build(
            stream,
            sink,
            async_executors::TokioTpBuilder::new().build().unwrap(),
        )
        .await
        .unwrap();
}
```

**Comment by obmarg** [comment]
I've never actually tried to use tokio with this lib, only async_std.  Kinda looks like that `TokioTpBuilder` is constructing a new runtime but then the runtime is being dropped immediately.

That's a shame - I kind of expected `async_executors` to provide a way to hook into the existing tokio runtime, so that we wouldn't need to store it anywhere.  Wonder if there's another `async_executor` that does this?  Or possibly we need to find somewhere to store the executor for tokio runtimes (could probably keep a hold of it inside the client if we wanted to - I only avoided doing that because I didn't think we'd need to)

**Comment by obmarg** [comment]
I've done a little bit more investigation into this and seems it's more tricky than I initially thought - `tokio::main` starts a runtime, but then `TokioTpBuilder::new().build()` starts another run time.  But because tokio uses thread locals to store the current runtime it's generally not a good idea to create one runtime within the other.

I guess a workaround would be to spawn another thread to run the `CynicClientBuilder` stuff, although that doesn't feel great.  Ideally `async_executors` would provide an executor that just uses the current tokio runtime.  I just tried to write one in `graphql-ws-client`  to test it out, but unfortunately too much of `async_executors` is private so there's no way for me to do this.  Might submit a PR upstream to fix...

**Comment by obmarg** [comment]
@BratSinot have a working tokio example over on #25 that you can probably take a look at?  Had to make some upstream changes to async_executors to get it to work
