### ISSUE TITLE
`AsyncWebsocketClientBuilder` is not `Send`

### ISSUE THREAD

**Issue by szgupta** [obmarg/graphql-ws-client#42]
Hi there! As I was playing around with the repo, I noticed that `AsyncWebsocketClientBuilder` is not `Send` because it has a field called `phantom` of type `PhantomData<*const GraphqlClient>`. Since `*const GraphqlClient` is not `Send` (because it's a pointer),  this causes the struct `AsyncWebsocketClientBuilder` itself to not be `Send`.

I think this isn't an issue with the `examples` in the repo because they use `async_std::main`/`tokio::main` which both internally use `block_on` under-the-hood. And `block_on` doesn't have `Send` requirements on the future, whereas the `spawn` equivalents do (tokio example [here](https://docs.rs/tokio/latest/tokio/fn.spawn.html)).

I think there's a few ways around this.
1. change the `phantom` type to `PhantomData<fn() -> GraphqlClient>`, which has the [same variance/drop constraints](https://doc.rust-lang.org/nomicon/phantom-data.html#table-of-phantomdata-patterns) as the current approach
2. explicitly mark `AsyncWebsocketClientBuilder` as `Send` via an `unsafe impl Send for AsyncWebsocketClientBuilder`

I think the first option is cleaner because the `AsyncWebsocketClientBuilder` will be `Send` for free if everything in it is also `Send`.

I'm happy to create a PR for this if you think one of these approaches is reasonable 😄

**Comment by Sytten** [comment]
Might be a dumb question but why cant we just use the type `PhantomData<GraphqlClient>`?

**Comment by szgupta** [comment]
@Sytten I believe it has to do with whether or not `drop check` analysis is factored in. More details [here](https://doc.rust-lang.org/std/marker/struct.PhantomData.html#ownership-and-the-drop-check). I'm not an expert in `PhantomData` usage so happy to re-consider the approach here. I think either work from a `Send` perspective.

**Comment by szgupta** [comment]
@obmarg I made a PR here: https://github.com/obmarg/graphql-ws-client/pull/43

Let me know what you think! I might be getting ahead of myself, but what are the steps for creating a new release (`0.3.0`) for this crate?

**Comment by obmarg** [comment]
> More details [here](https://doc.rust-lang.org/std/marker/struct.PhantomData.html#ownership-and-the-drop-check).

Ah, thanks for linking to this - I'd forgotten where it was I first saw the `*const` suggestion - it was this bit of documentation.  It's the reason I made it a `*const` in the first place, but I've since learned that is not great.  

Generally the way I've ended up thinking about this is that the `PhantomData` should mirror the relationship between the container and the type.  `PhantomData<GraphqlClient>` would imply that we own a `GraphqlClient`, which the `GraphqlClientBuilder` definitely doesn't.  `PhantomData<fn() -> GraphqlClient>` implies that we're creating a GQL client, so is a better choice.  Not sure if this is the best way to think about it, but I find it easier to remember than [the contents of this page](https://doc.rust-lang.org/nomicon/phantom-data.html) 😓.

Anyway, will get that PR merged and released soon, hopefully in the next hour or two.
